---

# VARIABLES TO EDIT
nomad_datacenter: "lab"
nomad_domain: "consul"
nomad_iface: eth1
nomad_network_interface: eth1
nomad_servers: ['server01.node.lab.consul:4647']
# CONSTANTS
nomad_consul_address: http://127.0.0.1:8500
nomad_vault_address: http://active.vault.service.lab.consul:8200
nomad_bind_address: "0.0.0.0"
nomad_use_consul: yes
nomad_vault_enabled: yes
nomad_options: {  'driver.raw_exec.enable': '1' }
nomad_network_speed: 10
nomad_bootstrap_expect: 1
nomad_docker_enable: yes
permanent: yes
nomad_ports_http: 4646
nomad_ports_rpc: 4647
nomad_ports_serf: 4648
# CREATE MANUALLY DURING BOOTSTRAP AFTER VAULT UNSEALING !!
nomad_vault_token: !vault |
          $ANSIBLE_VAULT;1.2;AES256;dev
          38323563616534643036666439316438323635636231373566386138333166333363363661613063
          3731396266336338333532353239656266613061333462660a373234353031643933306333333366
          37376566396635663335333239656164386564373661613438343938653537333731363536613834
          3566306432326464340a636633353833646434313638396633623831396536613438306431393665
          31353837663563343930336661646234363332393233353434633536626561643532
